"""Added index to gateway description

Revision ID: 2fd6f65b3cc0
Revises: ace2d84e5e1b
Create Date: 2020-03-25 19:55:25.785319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd6f65b3cc0'
down_revision = 'ace2d84e5e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_gateway_description'), 'gateway', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gateway_description'), table_name='gateway')
    # ### end Alembic commands ###
