"""Removed polygon and polygonpoint

Revision ID: 546f0d702405
Revises: 96390c8e1db7
Create Date: 2020-08-01 13:31:21.930163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '546f0d702405'
down_revision = '96390c8e1db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polygonpoint')
    op.drop_table('polygon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polygonpoint',
    sa.Column('pgp_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('polygon_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['polygon_id'], ['polygon.poly_id'], name='polygonpoint_ibfk_1'),
    sa.PrimaryKeyConstraint('pgp_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('polygon',
    sa.Column('poly_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fill_color', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('gtw_id', mysql.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['gtw_id'], ['gateway.gtw_id'], name='polygon_ibfk_1'),
    sa.PrimaryKeyConstraint('poly_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
