"""Added polygon and polygonpoint

Revision ID: 6916091fc891
Revises: d7868a861be1
Create Date: 2020-04-02 17:56:44.712873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6916091fc891'
down_revision = 'd7868a861be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polygon',
    sa.Column('poly_id', sa.Integer(), nullable=False),
    sa.Column('fill_color', sa.String(length=10), nullable=True),
    sa.Column('gtw_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['gtw_id'], ['gateway.gtw_id'], ),
    sa.PrimaryKeyConstraint('poly_id')
    )
    op.create_table('polygonpoint',
    sa.Column('pgp_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('polygon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['polygon_id'], ['polygon.poly_id'], ),
    sa.PrimaryKeyConstraint('pgp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polygonpoint')
    op.drop_table('polygon')
    # ### end Alembic commands ###
