"""Added last_seen to gateway

Revision ID: 81c4f42a30c6
Revises: 366b1b97f5c7
Create Date: 2020-03-25 19:48:41.184658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c4f42a30c6'
down_revision = '366b1b97f5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateway', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gateway', 'last_seen')
    # ### end Alembic commands ###
