"""Added placement to gateway

Revision ID: d7868a861be1
Revises: e0f0eedaf9be
Create Date: 2020-03-25 19:59:45.719507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7868a861be1'
down_revision = 'e0f0eedaf9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateway', sa.Column('placement', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_gateway_placement'), 'gateway', ['placement'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gateway_placement'), table_name='gateway')
    op.drop_column('gateway', 'placement')
    # ### end Alembic commands ###
