"""Added brand to gateway

Revision ID: d9a79112f018
Revises: 2fd6f65b3cc0
Create Date: 2020-03-25 19:57:04.637416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a79112f018'
down_revision = '2fd6f65b3cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateway', sa.Column('brand', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_gateway_brand'), 'gateway', ['brand'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gateway_brand'), table_name='gateway')
    op.drop_column('gateway', 'brand')
    # ### end Alembic commands ###
