"""Added antenna_model to gateway

Revision ID: e0f0eedaf9be
Revises: 88f90fd2bd43
Create Date: 2020-03-25 19:58:50.543451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f0eedaf9be'
down_revision = '88f90fd2bd43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateway', sa.Column('antenna_model', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_gateway_antenna_model'), 'gateway', ['antenna_model'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gateway_antenna_model'), table_name='gateway')
    op.drop_column('gateway', 'antenna_model')
    # ### end Alembic commands ###
