"""Change type of lat and lon in Message

Revision ID: fb430307223c
Revises: 546f0d702405
Create Date: 2020-08-01 13:38:43.059888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb430307223c'
down_revision = '546f0d702405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('message', 'longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'longitude',
               existing_type=sa.String(length=64),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('message', 'latitude',
               existing_type=sa.String(length=64),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
